import { styleValueFromTag, TXXX_SHORT_IDS } from './style-tag'

/**
 * Native tag IDs already mapped to a dedicated {@link AudioTags} field
 * (case-insensitive). Everything else is surfaced as a custom tag.
 */
export const MAPPED_NATIVE_TAGS = new Set(
  [
    // ID3v1
    'YEAR',
    // ID3v2.3/v2.4
    'TIT2',
    'TPE1',
    'TSOP',
    'TALB',
    'TSOA',
    'TRCK',
    'TPOS',
    'TYER',
    'TDRC',
    'TBPM',
    'TCON',
    'TXXX:STYLE',
    'TPE2',
    'TSO2',
    'TCOM',
    'TPE3',
    'COMM',
    'TIT1',
    'GRP1',
    'TPUB',
    'TSST',
    'TEXT',
    'TDOR',
    'TORY',
    'TCOP',
    'POPM',
    'USLT',
    'SYLT',
    'TCMP',
    'TENC',
    'APIC',
    // ID3v2.2
    'TT2',
    'TP1',
    'TSP',
    'TAL',
    'TSA',
    'TRK',
    'TPA',
    'TYE',
    'TBP',
    'TCO',
    'TP2',
    'TS2',
    'TCM',
    'TP3',
    'COM',
    'TT1',
    'GP1',
    'TPB',
    'TXT',
    'TOR',
    'TCR',
    'TCP',
    'TEN',
    'PIC',
    // Vorbis/FLAC
    'TITLE',
    'ARTIST',
    'ARTISTSORT',
    'ALBUM',
    'ALBUMSORT',
    'TRACKNUMBER',
    'DISCNUMBER',
    'DATE',
    'BPM',
    'GENRE',
    'STYLE',
    'ALBUMARTIST',
    'ALBUM ARTIST',
    'PUBLISHER',
    'ALBUMARTISTSORT',
    'COMPOSER',
    'CONDUCTOR',
    'COMMENT',
    'GROUPING',
    'LABEL',
    'CATALOGNUMBER',
    'CATALOGID',
    'LYRICIST',
    'BARCODE',
    'WORK',
    'ORIGINALDATE',
    'ORIGINALYEAR',
    'COPYRIGHT',
    'RATING',
    'LYRICS',
    'COMPILATION',
    'ENCODEDBY',
    'METADATA_BLOCK_PICTURE',
    // iTunes/M4A
    '©NAM',
    '©ART',
    'SOAR',
    '©ALB',
    'SOAL',
    'TRKN',
    'DISK',
    'TMPO',
    '©GEN',
    'GNRE',
    'AART',
    'SOAA',
    '©WRT',
    '©CMT',
    '©COM',
    '©GRP',
    '©WRK',
    'CPRT',
    '©CPY',
    'RATE',
    '©LYR',
    'CPIL',
    'PGAP',
    '©TOO',
    'COVR',
    // APEv2
    'TRACK',
    'DISC',
    'ALBUM ARTIST',
    'CATALOGNUMBER',
    'ORIGINALDATE',
    'ORIGINALYEAR',
    'ENCODEDBY',
    'COVER ART (FRONT)',
    'COVER ART (BACK)',
    // Opus
    'TRACKTOTAL',
    'TOTALTRACKS',
    'ORGANIZATION',
    'DISCTOTAL',
    // TXXX subtags
    'TXXX:BARCODE',
    'TXXX:CATALOGNUMBER',
    'TXXX:DISCOGS_CATALOG',
    'TXXX:CATALOGID',
    'TXXX:ORIGINALDATE',
    'TXXX:ORIGINALYEAR',
    'TXXX:WORK',
    'TXXX:RATING',
    // RIFF/INFO (WAV exif tags)
    'IART',
    'ICRD',
    'INAM',
    'TITL',
    'IPRD',
    'ITRK',
    'IPRT',
    'COMM',
    'ICMT',
    'ICNT',
    'GNRE',
    'IWRI',
    'RATE',
    'ISFT',
    'CODE',
    'TURL',
    'IGNR',
    'IENG',
    'ITCH',
    'IMED',
    'IRPD',
    'DIRC',
    'ICNM',
    'ICOP',
    'ISTR',
    'IFRM',
    // iTunes custom tags
    '----:COM.APPLE.ITUNES:CONDUCTOR',
    '----:COM.APPLE.ITUNES:NOTES',
    '----:COM.APPLE.ITUNES:LABEL',
    '----:COM.APPLE.ITUNES:CATALOGNUMBER',
    '----:COM.APPLE.ITUNES:LYRICIST',
    '----:COM.APPLE.ITUNES:BARCODE',
    '----:COM.APPLE.ITUNES:ORIGINALDATE',
    '----:COM.APPLE.ITUNES:ORIGINALYEAR',
    '----:COM.APPLE.ITUNES:ALBUMARTISTSORT',
    '----:COM.APPLE.ITUNES:BAND',
    '----:com.apple.iTunes:RATING',
    '----:com.apple.iTunes:WORK',
    '----:com.apple.iTunes:publisher',
    'cond',
    '©day',
    // ASF/WMA
    'AUTHOR',
    'DESCRIPTION',
    'TITLE',
    'COPYRIGHT',
    'WM/ALBUMARTIST',
    'WM/ALBUMARTISTSORTORDER',
    'WM/ALBUMSORTORDER',
    'WM/ALBUMTITLE',
    'WM/ARTISTSORTORDER',
    'WM/BARCODE',
    'WM/BEATSPERMINATE',
    'WM/CATALOGNO',
    'WM/COMPOSER',
    'WM/CONDUCTOR',
    'WM/CONTENTGROUPDESCRIPTION',
    'WM/ENCODEDBY',
    'WM/ENCODINGSETTINGS',
    'WM/GENRE',
    'WM/ISCOMPILATION',
    'WM/LYRICS',
    'WM/ORIGINALRELEASETIME',
    'WM/ORIGINALRELEASEYEAR',
    'WM/PARTOFSET',
    'WM/PUBLISHER',
    'WM/SHAREDUSERRATING',
    'WM/TEXT',
    'WM/TRACKNUMBER',
    'WM/WORK',
    'WM/WRITER',
    'WM/BEATSPERMINUTE',
    'WM/YEAR',
    'WM/PICTURE'
  ].map(t => t.toUpperCase())
)

/** True when a native tag already has a dedicated field and must not be duplicated as a custom tag. */
export function isMappedNativeTag(tagId: string, value: string): boolean {
  const upperId = tagId.toUpperCase()
  if (MAPPED_NATIVE_TAGS.has(upperId)) return true

  // Style has its own field, so its native frame must not also be surfaced as a
  // generic custom tag (covers the iTunes/ASF ID variants).
  if (styleValueFromTag({ id: tagId, value }) !== undefined) return true

  // For TXX/TXXX frames, check whether TXXX:DESCRIPTION is mapped.
  if (TXXX_SHORT_IDS.has(upperId)) {
    const nullIndex = value.indexOf('\0')
    const description = nullIndex >= 0 ? value.substring(0, nullIndex) : value
    return MAPPED_NATIVE_TAGS.has(`TXXX:${description.toUpperCase()}`)
  }

  return false
}
